name: Periodic Health Check

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes (for testing)

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check application health
        uses: Jtalk/url-health-check-action@v4
        with:
          url: 'https://pokedex-4vqf.onrender.com/health'
          max-attempts: 3
          retry-delay: 5s
          follow-redirect: true

