name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

env:
   SKIP_DEPLOYMENT: ${{ contains(github.event.head_commit.message, '#skip') }}

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'


      - name: Install dependencies
        run: |
          cd full-stack-open-pokedex
          npm ci

      - name: Install Playwright browsers
        run: |
          cd full-stack-open-pokedex
          npx playwright install

      - name: Run Playwright tests
        run: |
          cd full-stack-open-pokedex
          npm run test:e2e

      - name: Check style
        run: |
          cd full-stack-open-pokedex
          npm run eslint

      - name: Run tests
        run: |
          cd full-stack-open-pokedex
          npm test

      - name: Build project
        run: |
          cd full-stack-open-pokedex
          npm run build

      - name: Trigger Render deployment
        if: github.event_name == 'push' && env.SKIP_DEPLOYMENT == 'false'
        run: |
          curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}

      - name: Notify Discord on Success
        if: success()
        uses: rjstone/discord-webhook-notify@v1.0.4
        with:
          severity: info
          details: "✅ Deployment successful!\n🚀 **Deployed by:** ${{ github.actor }}\n🔗 **Events page in Render:** [View in Render](https://dashboard.render.com/web/srv-${{ secrets.RENDER_SERVICE_ID }})"
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Notify Discord on Failure
        if: failure()
        uses: rjstone/discord-webhook-notify@v1.0.4
        with:
          severity: error
          details: "❌ Deployment failed!\n👤 **Committed by:** ${{ github.actor }}\n🔗 **Failed commit:** [View commit](https://github.com/${{ github.repository }}/commit/${{ github.sha }})"
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
    

  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all commit history and tags. last test

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@f278d49d30cdd8775cc3e7dd00b5ee11686ee297
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch  # Ensures only a patch version bump