name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

env:
   SKIP_DEPLOYMENT: ${{ contains(github.event.head_commit.message, '#skip') }}

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'


      - name: Install dependencies
        run: |
          cd full-stack-open-pokedex
          npm ci

      - name: Install Playwright browsers
        run: |
          cd full-stack-open-pokedex
          npx playwright install

      - name: Run Playwright tests
        run: |
          cd full-stack-open-pokedex
          npm run test:e2e

      - name: Check style
        run: |
          cd full-stack-open-pokedex
          npm run eslint

      - name: Run tests
        run: |
          cd full-stack-open-pokedex
          npm test

      - name: Build project
        run: |
          cd full-stack-open-pokedex
          npm run build

      - name: Trigger Render deployment
        if: github.event_name == 'push' && env.SKIP_DEPLOYMENT == 'false'
        run: |
          curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}

  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/main'  # Remove SKIP_DEPLOYMENT check for now
    steps:
      - name: Debug GitHub env variables
        run: echo "github.env.SKIP_DEPLOYMENT is ${{env.SKIP_DEPLOYMENT }}"
    
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all commit history and tags

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch  # Ensures only a patch version bump