name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd full-stack-open-pokedex
          npm ci  # Ensures a clean install, including Playwright

      - name: Install Playwright browsers
        run: |
          cd full-stack-open-pokedex
          npx playwright install  # Download the necessary browsers

      - name: Run Playwright tests
        run: |
          cd full-stack-open-pokedex
          npm run test:e2e  # Assumes you have a script to run Playwright tests

      - name: Check style
        run: |
          cd full-stack-open-pokedex
          npm run eslint

      - name: Run tests
        run: |
          cd full-stack-open-pokedex
          npm test

      - name: Build project
        run: |
          cd full-stack-open-pokedex
          npm run build

      - name: Trigger Render deployment
        if: github.event_name == 'push'
        run: |
          curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}

  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch # testing with permissions
          DRY_RUN: false  # Set to true if you want to test without tagging a new version
